.Dd September 14, 2026
.Dt BUFFER-MUTATIONS 1
.Os
.Sh NAME
.Nm buffer-mutations
.Nd native buffer observer probe
.Sh DESCRIPTION
.No OVERLAY-A\zX Ns B
.Pp
.No ZERO-A\&B
.Pp
.No EMPTY-A "" B
.Pp
.No FONT-A\zX Ns \fBB\fP
.Pp
.No OVERSTRIKE-\o'AB'
.Pp
.No REPLACE-A\h'-1n'B
.Pp
.Lk https://example.org/path LINK-A\zX Ns B
