.Dd September 19, 2026
.Dt K18 1
.Os
.Sh NAME
.Nm k18
.Nd responsive definition boundary probe
.Sh DESCRIPTION
.Bl -tag -width 8n
.It Xo
.No alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau upsilon phi chi psi omega alpha beta gamma delta epsilon zeta
.Xc
First body line.
.br
Second body line.
.El
