.Dd September 13, 2026
.Dt K12-HEADING 1
.Os ManT
.Sh NAME
.Nm k12-heading
.Nd native heading execution
.Sh Fl An Alice
.No FLAGBODY
.Sh Pf $ An Alice
.No PREFIXBODY
.Sh PARENT\fI
\fPSECTION-BODY
.Ss CHILD\fI
\fPSUB-BODY
.Sh NEXT SECTION
.No FIRST
.Sh NEXTSECTION
.No SECOND
.Sh AUTHORS
.Sh Dq An -split An Alice
.An Bob
.Sh SPACING
.Sm off
.No one two
.Sh NEXT
.No three four
.Sh SEE ALSO
.Sx NEXT SECTION
