.TH TEST 1 "2026-10-03"
.SH DESCRIPTION
.TS
l.
T{
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
.B WORD
T}
.TE
AFTER
