//! Owned facts captured from one authoritative native terminal execution.

use std::{fmt, ops::Range, path::PathBuf};

/// Sentinel-free report-local identity of a syntax node.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ExecutionNodeKey(pub u32);

/// Report-local identity of a buffered atom.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct AtomKey(pub u32);

/// Report-local identity of an emitted fragment.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct FragmentKey(pub u32);

/// Half-open byte range in the report's immutable byte pool.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PoolRange {
    /// First byte.
    pub start: u32,
    /// Number of bytes.
    pub length: u32,
}

impl PoolRange {
    pub(crate) fn as_range(self) -> Option<Range<usize>> {
        let start = usize::try_from(self.start).ok()?;
        let end = start.checked_add(usize::try_from(self.length).ok()?)?;
        Some(start..end)
    }
}

/// Kind of one native terminal-buffer atom.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AtomKind {
    /// Printable glyph.
    Glyph,
    /// Breakable space.
    BreakableSpace,
    /// Non-breaking space.
    NonBreakingSpace,
    /// Discretionary hyphen.
    BreakableHyphen,
    /// Non-printing zero-width marker.
    ZeroWidth,
    /// Literal tab.
    Tab,
    /// Tab-origin reference marker.
    TabReference,
    /// Backspace used by terminal overstrike.
    Backspace,
    /// Word-end line-break request produced by `\p`.
    WordEndBreak,
    /// Zero-width discretionary break point produced by `\:`.
    BreakPoint,
}

/// Why an atom entered the native buffer.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AtomRole {
    /// Derived from a formatter word operand.
    Authored,
    /// Implicit inter-word spacing.
    ImplicitSpace,
    /// Device overstrike used to express a font.
    FontDecoration,
    /// Text generated by a manual macro handler.
    MacroGenerated,
    /// Text generated by the output device.
    DeviceGenerated,
}

/// Final fate of one atom in the captured execution.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AtomDisposition {
    /// Still buffered when the report was sealed.
    Buffered,
    /// Emitted by the device.
    Emitted,
    /// Consumed as layout input without visible output.
    Consumed,
    /// Replaced by a later buffer mutation.
    Replaced,
    /// Discarded as trailing layout whitespace.
    TrailingDiscard,
}

/// Effective terminal font at an execution point.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutionFont {
    /// Roman/default.
    Roman,
    /// Bold.
    Bold,
    /// Underline/italic terminal projection.
    Underline,
    /// Bold underline.
    BoldUnderline,
}

/// Why one fragment was emitted by the native device.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FragmentRole {
    /// Document content.
    Content,
    /// Device decoration used to project a font.
    FontDecoration,
    /// A margin character generated by `.mc`.
    MarginDecoration,
    /// A page header or footer generated by the terminal device.
    PageDecoration,
}

/// Native newline or vertical-space request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BoundaryRequest {
    /// Conditional newline.
    Newline,
    /// Unconditional vertical space.
    VerticalSpace,
    /// Native `endline()` operation, including margin output.
    Endline,
    /// Device line completion.
    DeviceEndline,
}

/// Observed result of a boundary request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BoundaryEffect {
    /// State changed without output.
    NoOutput,
    /// Buffered content was flushed.
    Flushed,
    /// A device line ended.
    EndedLine,
    /// A blank device line was added.
    AddedVerticalSpace,
}

/// Kind of a native geometry observation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeometryKind {
    /// Horizontal advance.
    Advance,
    /// Glyph placement.
    Glyph,
    /// Device line completion.
    Endline,
    /// Field geometry.
    Field,
}

/// Unit carried by a geometry observation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeometryUnit {
    /// Native terminal basic units.
    Basic,
    /// Native buffer slot.
    BufferSlot,
    /// Device line number.
    DeviceLine,
}

/// Type of report record causing one geometry observation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeometryOriginKind {
    /// No record-level origin is available.
    None,
    /// A terminal-buffer atom.
    Atom,
    /// A native flush segment.
    Flush,
    /// A boundary request.
    Boundary,
    /// An emitted fragment.
    Fragment,
}

/// Stable kind of an execution scope or instantaneous state transition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutionWrapperKind {
    /// Syntax-node execution interval.
    Node,
    /// Instantaneous font-stack transition.
    Font,
}

/// Semantic destination kind observed at the native macro handler.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutionReferenceKind {
    /// External URI.
    ExternalUri,
    /// Email address.
    Email,
    /// Manual name and optional section.
    Manual,
    /// Same-document section phrase.
    SameDocumentSection,
}

/// Relationship between an execution fact and surrounding emitted content.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutionAffinity {
    /// The fact spans inline formatter atoms.
    Inline,
    /// The fact attaches before the next output owned by its node.
    BeforeOutput,
}

/// One input source participating in the execution.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionSource {
    /// Report-local source key.
    pub key: u32,
    /// Including source, absent for the root.
    pub parent: Option<u32>,
    /// Node issuing the include, absent for the root.
    pub include_node: Option<ExecutionNodeKey>,
    /// Logical source path.
    pub path: PathBuf,
}

/// Stable structural identity and source location for one syntax node.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionNode {
    /// Dense report-local node key.
    pub key: ExecutionNodeKey,
    /// Parent node.
    pub parent: Option<ExecutionNodeKey>,
    /// Source key.
    pub source: u32,
    /// One-based source line, or zero when unavailable.
    pub line: u32,
    /// One-based source column, or zero when unavailable.
    pub column: u32,
    /// Stable node-kind code shared with the owned AST snapshot.
    pub kind: u32,
    /// Stable node flags.
    pub flags: u32,
    /// Source macro name, when applicable.
    pub macro_name: Option<String>,
}

/// One lifetime of a native terminal column buffer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionBufferGeneration {
    /// Dense report-local generation key.
    pub key: u32,
    /// Native terminal column buffer identity.
    pub buffer: u32,
    /// Monotonic generation within that buffer.
    pub generation: u32,
    /// Allocated native cells available to this generation.
    pub capacity: u32,
    /// Highest logical half-open buffer position observed.
    pub extent: u32,
    /// Why this generation ended.
    pub close_reason: BufferCloseReason,
    /// Execution interval containing every fact referring to this generation.
    pub open_sequence: u64,
    /// Execution point at which the generation was reset or the report sealed.
    pub close_sequence: u64,
}

/// Why a native buffer generation ended.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BufferCloseReason {
    /// `term_flushln()` reset the buffer after consuming the field.
    Reset,
    /// The report was sealed while the reusable buffer remained allocated.
    ReportEnd,
}

/// One native terminal-buffer atom and its provenance.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionAtom {
    /// Atom identity.
    pub key: AtomKey,
    /// Native terminal column-buffer identity.
    pub buffer: Option<u32>,
    /// Buffer generation.
    pub generation: Option<u32>,
    /// Owning buffer-generation fact, absent for direct device output.
    pub buffer_generation: Option<u32>,
    /// Buffer slot, absent for direct device output.
    pub slot: Option<u32>,
    /// Atom kind.
    pub kind: AtomKind,
    /// Atom origin role.
    pub role: AtomRole,
    /// Scalar before device normalization.
    pub input_scalar: u32,
    /// Scalar emitted to the device.
    pub display_scalar: u32,
    /// Width in native basic units.
    pub width_bu: i64,
    /// Owning syntax node.
    pub node: Option<ExecutionNodeKey>,
    /// Source key.
    pub source: u32,
    /// Formatter word bytes associated with this atom.
    pub operand: Option<PoolRange>,
    /// Effective font.
    pub font: ExecutionFont,
    /// Innermost wrapper key.
    pub wrapper: Option<u32>,
    /// Replacing atom, when overwritten.
    pub replaced_by: Option<AtomKey>,
    /// Final atom disposition.
    pub disposition: AtomDisposition,
    /// Total execution order.
    pub sequence: u64,
}

/// One device-emitted fragment.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionFragment {
    /// Fragment identity.
    pub key: FragmentKey,
    /// Owning syntax node.
    pub node: Option<ExecutionNodeKey>,
    /// Native buffer identity and generation.
    pub buffer: Option<u32>,
    /// Native buffer generation.
    pub generation: Option<u32>,
    /// Owning buffer-generation fact, absent for direct device output.
    pub buffer_generation: Option<u32>,
    /// Atom keys contributing to this fragment.
    pub atoms: Vec<AtomKey>,
    /// One-based device line.
    pub device_line: u32,
    /// Whether this is content or device decoration.
    pub role: FragmentRole,
    /// Start position in basic units.
    pub start_bu: i64,
    /// End position in basic units.
    pub end_bu: i64,
    /// Innermost wrapper key.
    pub wrapper: Option<u32>,
    /// Total execution order.
    pub sequence: u64,
}

/// One accepted field segment from `term_fill`/`term_field`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionFlush {
    /// Flush-segment identity.
    pub key: u32,
    /// Owning node.
    pub node: Option<ExecutionNodeKey>,
    /// Native buffer and generation.
    pub buffer: u32,
    /// Native buffer generation.
    pub generation: u32,
    /// Owning buffer-generation fact.
    pub buffer_generation: u32,
    /// Buffer range scanned by the native fill algorithm.
    pub scanned: Range<u32>,
    /// Buffer range accepted for this field segment.
    pub accepted: Range<u32>,
    /// Buffer range consumed by the device.
    pub consumed: Range<u32>,
    /// Buffer range remaining for subsequent segments.
    pub remaining: Range<u32>,
    /// Emitted fragment range.
    pub fragments: Range<u32>,
    /// Stable terminal flags before the flush.
    pub flags_before: u32,
    /// Stable terminal flags after the flush.
    pub flags_after: u32,
    /// Boundary causally containing this flush.
    pub boundary: Option<u32>,
    /// Actual fixed-CVS branch taken after this fill decision.
    pub outcome: FlushOutcome,
    /// Leading space in basic units.
    pub leading_bu: i64,
    /// Accepted content width in basic units.
    pub content_bu: i64,
    /// Field width in basic units.
    pub field_bu: i64,
    /// Target width in basic units.
    pub target_bu: i64,
    /// Tab offset before the segment.
    pub taboff_before: i64,
    /// Tab offset after the segment.
    pub taboff_after: i64,
    /// Visual position before/after the segment.
    pub visual_before: i64,
    /// Visual position after the segment.
    pub visual_after: i64,
    /// Total execution order.
    pub sequence: u64,
    /// Execution point at which the branch outcome became known.
    pub outcome_sequence: u64,
}

/// Actual branch taken by one native `term_flushln()` fill segment.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FlushOutcome {
    /// `term_fill()` accepted no visible field content.
    NoContent,
    /// The accepted field exhausted all non-layout content.
    Exhausted,
    /// Single-column output ended a device line and continued this buffer.
    Wrapped,
    /// Multi-column output yielded the remaining buffer to another column.
    DeferredColumn,
}

/// One ordered native boundary request and its observed effect.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionBoundary {
    /// Boundary identity.
    pub key: u32,
    /// Owning node.
    pub node: Option<ExecutionNodeKey>,
    /// Causal parent boundary, when any.
    pub parent: Option<u32>,
    /// Request kind.
    pub request: BoundaryRequest,
    /// Observed effect.
    pub effect: BoundaryEffect,
    /// Stable terminal flags before the request.
    pub flags_before: u32,
    /// Stable terminal flags after the request.
    pub flags_after: u32,
    /// Device line before/after.
    pub line_before: i64,
    /// Device line after.
    pub line_after: i64,
    /// Visual position before/after.
    pub visual_before: i64,
    /// Visual position after.
    pub visual_after: i64,
    /// Total execution order.
    pub sequence: u64,
}

/// One objective native geometry observation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionGeometry {
    /// Geometry identity.
    pub key: u32,
    /// Owning node.
    pub node: Option<ExecutionNodeKey>,
    /// Related flush, boundary, fragment, or atom key.
    pub related: Option<u32>,
    /// Observation kind.
    pub kind: GeometryKind,
    /// Numeric unit.
    pub unit: GeometryUnit,
    /// Stable kind of the record that caused this observation.
    pub origin_kind: GeometryOriginKind,
    /// Report-local key of the causing record.
    pub origin_key: Option<u32>,
    /// Requested and effective values.
    pub requested: i64,
    /// Effective value.
    pub effective: i64,
    /// Coordinate before the operation.
    pub before: i64,
    /// Coordinate after the operation.
    pub after: i64,
    /// Total execution order.
    pub sequence: u64,
}

/// Execution scope or instantaneous state transition for a syntax node,
/// font, or link.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionWrapper {
    /// Wrapper identity.
    pub key: u32,
    /// Parent wrapper.
    pub parent: Option<u32>,
    /// Owning syntax node.
    pub node: Option<ExecutionNodeKey>,
    /// Stable wrapper-kind code.
    pub kind: ExecutionWrapperKind,
    /// Optional target or label bytes associated with the wrapper.
    pub target: Option<PoolRange>,
    /// Atom cursor on entry and leave.
    pub enter_atom: u32,
    /// Atom cursor on leave.
    pub leave_atom: u32,
    /// Stable attachment affinity.
    pub affinity: u32,
    /// Stable wrapper flags.
    pub flags: u32,
    /// Effective state before and after state transitions.
    pub state_before: u32,
    /// Effective state after the transition.
    pub state_after: u32,
    /// Stack depth before and after the transition.
    pub depth_before: u32,
    /// Stack depth after the transition.
    pub depth_after: u32,
    /// Total execution order on entry and leave.
    pub enter_sequence: u64,
    /// Total execution order on leave.
    pub leave_sequence: u64,
}

/// One semantic reference and the exact formatter-atom interval used as its
/// visible label.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionReference {
    /// Dense report-local reference key.
    pub key: u32,
    /// Enclosing reference when native inline macros are nested.
    pub parent: Option<u32>,
    /// Macro node that created the reference.
    pub owner_node: ExecutionNodeKey,
    /// Syntax node carrying the primary authored target.
    pub target_node: ExecutionNodeKey,
    /// Semantic destination kind.
    pub kind: ExecutionReferenceKind,
    /// Primary authored target bytes.
    pub primary: PoolRange,
    /// Optional second target component, such as a manual section.
    pub secondary: Option<PoolRange>,
    /// Complete half-open atom interval executed while this reference was open.
    pub execution_atoms: Range<u32>,
    /// Half-open interval used as the visible label, excluding the leading
    /// implicit word-boundary space emitted by `term_word()`.
    pub atoms: Range<u32>,
    /// Attachment affinity.
    pub affinity: ExecutionAffinity,
    /// Total execution order on entry and leave.
    pub enter_sequence: u64,
    /// Total execution order on leave.
    pub leave_sequence: u64,
}

/// One source target attached during native execution.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionAnchor {
    /// Dense report-local anchor key.
    pub key: u32,
    /// Owning syntax node.
    pub node: ExecutionNodeKey,
    /// Authored target bytes.
    pub target: PoolRange,
    /// One-based device line at the actual terminal tag attachment.
    pub device_line: u32,
    /// Atom cursor at attachment time.
    pub atom_cursor: u32,
    /// Fragment cursor at attachment time.
    pub fragment_cursor: u32,
    /// Stable attachment affinity.
    pub affinity: ExecutionAffinity,
    /// Total execution order.
    pub sequence: u64,
}

/// One non-fatal diagnostic produced while building the execution report.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionDiagnostic {
    /// Stable diagnostic code.
    pub code: u32,
    /// Related syntax node, when available.
    pub node: Option<ExecutionNodeKey>,
    /// Diagnostic message bytes.
    pub message: PoolRange,
    /// Total execution order.
    pub sequence: u64,
}

/// Fully owned result of one parse and one native terminal traversal.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NativeExecutionReport {
    pub(crate) pool: Vec<u8>,
    /// Native work units charged by this execution.
    pub work_units: u64,
    /// Total records stored across all typed tables.
    pub record_count: u64,
    /// Peak native terminal buffer capacity charged to this execution.
    pub buffer_cells: u64,
    /// Participating sources.
    pub sources: Vec<ExecutionSource>,
    /// Final-tree node registry.
    pub nodes: Vec<ExecutionNode>,
    /// Native buffer lifetimes referenced by atoms, fragments, and flushes.
    pub buffer_generations: Vec<ExecutionBufferGeneration>,
    /// Buffer atoms.
    pub atoms: Vec<ExecutionAtom>,
    /// Device fragments.
    pub fragments: Vec<ExecutionFragment>,
    /// Native field segments.
    pub flushes: Vec<ExecutionFlush>,
    /// Ordered boundary requests and effects.
    pub boundaries: Vec<ExecutionBoundary>,
    /// Objective native geometry.
    pub geometry: Vec<ExecutionGeometry>,
    /// Execution scopes and instantaneous state transitions.
    pub wrappers: Vec<ExecutionWrapper>,
    /// Semantic references observed at their native macro handlers.
    pub references: Vec<ExecutionReference>,
    /// Native target attachments.
    pub anchors: Vec<ExecutionAnchor>,
    /// Non-fatal report diagnostics.
    pub diagnostics: Vec<ExecutionDiagnostic>,
}

impl NativeExecutionReport {
    /// Number of bytes in the immutable report pool.
    #[must_use]
    pub fn pool_len(&self) -> usize {
        self.pool.len()
    }

    /// Whether the immutable report pool is empty.
    #[must_use]
    pub fn pool_is_empty(&self) -> bool {
        self.pool.is_empty()
    }

    /// Borrow bytes from the immutable report pool.
    #[must_use]
    pub fn pool_bytes(&self, range: PoolRange) -> Option<&[u8]> {
        self.pool.get(range.as_range()?)
    }
}

/// Limits independently bounding native execution work and storage.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutionLimits {
    /// Maximum final-tree nodes.
    pub max_nodes: u64,
    /// Maximum syntax-tree depth.
    pub max_depth: u64,
    /// Maximum charged native work units.
    pub max_work: u64,
    /// Maximum records across all typed tables.
    pub max_records: u64,
    /// Maximum pooled source and operand bytes.
    pub max_pool_bytes: u64,
    /// Maximum tracked native buffer cells.
    pub max_buffer_cells: u64,
}

impl Default for ExecutionLimits {
    fn default() -> Self {
        Self {
            max_nodes: 1_000_000,
            max_depth: 256,
            max_work: 16_000_000,
            max_records: 4_000_000,
            max_pool_bytes: 16 * 1024 * 1024,
            max_buffer_cells: 1_000_000,
        }
    }
}

/// A document and the facts produced by its single native execution.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionReport {
    /// Fully owned parsed syntax tree.
    pub document: crate::Document,
    /// Non-fatal parser diagnostics.
    pub diagnostics: Vec<crate::Diagnostic>,
    /// Fully owned native execution facts.
    pub execution: NativeExecutionReport,
}

/// Stable failure category for the combined parse/execute boundary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutionErrorKind {
    /// Input policy cannot be represented by this execution version.
    Unsupported,
    /// A configured execution budget was exhausted.
    Budget,
    /// Native storage could not be allocated.
    Allocation,
    /// Parsing or native execution failed.
    Native,
    /// The C/Rust transfer contract was rejected.
    Transfer,
}

/// Failure from the combined parse/execute boundary.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionError {
    /// Logical source path.
    pub path: PathBuf,
    /// Stable category.
    pub kind: ExecutionErrorKind,
    /// Human-readable detail.
    pub message: String,
}

impl fmt::Display for ExecutionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}: {}", self.path.display(), self.message)
    }
}

impl std::error::Error for ExecutionError {}
