//! Section/root ownership and source-ordered heading reconstruction.
use super::{
    Block, LoweringContext, Node, NodeKind, ScopeFlow, Section, first_part_children, lower_scope,
    section_spacing, source_span, update_paragraph_distance,
};
use crate::mandoc::inline::authored_section_phrase;

pub(in crate::mandoc) fn lower_document_structure(
    root: &Node,
    context: &mut LoweringContext<'_>,
) -> (Vec<Block>, Vec<Section>) {
    let mut paragraph_distance = 1;
    let mut root_paragraph_distance = 1;
    let mut formatter = crate::mandoc::formatter::FormatterState::default();
    let mut root_blocks = Vec::new();
    let mut sections = Vec::new();
    let mut root_start = 0;
    for (index, node) in root.children.iter().enumerate() {
        update_paragraph_distance(node, &mut paragraph_distance);
        // Accept both `.SH` and a `.SS` that appears directly at the document
        // root. Well-formed pages nest `.SS` inside a `.SH` body, but pages
        // generated by tools such as Pandoc emit only `.SS` blocks with no
        // enclosing `.SH`. Without this, such pages lower to zero sections and
        // the whole document is reported as unreadable.
        if !is_section(node, true) && !is_section(node, false) {
            continue;
        }
        let spacing_enabled = formatter.spacing_enabled();
        root_blocks.extend(lower_scope(
            &root.children[root_start..index],
            context,
            &mut root_paragraph_distance,
            &mut formatter,
            ScopeFlow::settled(
                crate::mandoc::layout::SourceIndent::default(),
                spacing_enabled,
            ),
        ));
        root_start = index + 1;
        let has_preceding_content = sections.last().is_some_and(section_has_body);
        let spacing_before_lines = section_spacing(
            node,
            sections.is_empty(),
            has_preceding_content,
            paragraph_distance,
        );
        sections.push(lower_section(
            node,
            context,
            spacing_before_lines,
            &mut paragraph_distance,
            &mut formatter,
            true,
        ));
    }
    let spacing_enabled = formatter.spacing_enabled();
    root_blocks.extend(lower_scope(
        &root.children[root_start..],
        context,
        &mut root_paragraph_distance,
        &mut formatter,
        ScopeFlow::settled(
            crate::mandoc::layout::SourceIndent::default(),
            spacing_enabled,
        ),
    ));
    (root_blocks, sections)
}

fn lower_section(
    node: &Node,
    context: &mut LoweringContext<'_>,
    spacing_before_lines: u16,
    paragraph_distance: &mut u16,
    formatter: &mut crate::mandoc::formatter::FormatterState,
    top_level: bool,
) -> Section {
    let head = first_part_children(node, NodeKind::Head);
    let section_context = if top_level {
        native_mdoc_section_context(node)
    } else {
        context.active_mdoc_section()
    };
    let authored_title = authored_section_phrase(head, context.default_name);
    let heading = context.lower_section_heading(
        head,
        formatter,
        section_context == crate::mandoc::source_context::MdocSectionContext::Authors,
    );
    // Allocate IDs in visible document order. Besides being deterministic for
    // consumers, this makes `.Sx` resolution independent of tree recursion.
    let (id, fragment_aliases) = context.section_identity_for(&authored_title, node);
    let body = first_part_children(node, NodeKind::Body);
    let first_subsection = body
        .iter()
        .position(|child| is_section(child, false))
        .unwrap_or(body.len());
    let previous_section = context.replace_mdoc_section(section_context);
    if top_level && section_context == crate::mandoc::source_context::MdocSectionContext::Authors {
        formatter.enter_authors_section();
    }
    let spacing_enabled = formatter.spacing_enabled();
    let blocks = lower_scope(
        &body[..first_subsection],
        context,
        paragraph_distance,
        formatter,
        ScopeFlow::settled(
            crate::mandoc::layout::SourceIndent::default(),
            spacing_enabled,
        ),
    );
    let mut has_preceding_content = !blocks.is_empty();
    let mut children = Vec::new();
    for child in &body[first_subsection..] {
        update_paragraph_distance(child, paragraph_distance);
        if !is_section(child, false) {
            continue;
        }
        let child_spacing = section_spacing(
            child,
            children.is_empty(),
            has_preceding_content,
            *paragraph_distance,
        );
        let child = lower_section(
            child,
            context,
            child_spacing,
            paragraph_distance,
            formatter,
            false,
        );
        has_preceding_content = section_has_body(&child);
        children.push(child);
    }
    context.replace_mdoc_section(previous_section);
    Section {
        id: id.into(),
        fragment_aliases,
        heading: mant_ir::Heading {
            content: heading,
            source: node
                .children
                .iter()
                .find(|child| child.kind == NodeKind::Head)
                .and_then(source_span),
        },
        spacing_before_lines,
        blocks,
        children,
        source: source_span(node),
    }
}

/// Consume the parser's normalized `sec` rather than reconstructing it from
/// the authored heading. CVS `mdoc_state.c::state_sh()` already decided when
/// a direct text head names a standard section.
fn native_mdoc_section_context(node: &Node) -> crate::mandoc::source_context::MdocSectionContext {
    match node.section {
        libmandoc_rs::NormalizedSection::Synopsis => {
            crate::mandoc::source_context::MdocSectionContext::Synopsis
        }
        libmandoc_rs::NormalizedSection::Authors => {
            crate::mandoc::source_context::MdocSectionContext::Authors
        }
        _ => crate::mandoc::source_context::MdocSectionContext::Other,
    }
}

fn section_has_body(section: &Section) -> bool {
    !section.blocks.is_empty() || section.children.iter().any(section_has_body)
}

pub(super) fn is_section(node: &Node, top_level: bool) -> bool {
    matches!(
        (node.macro_name.as_deref(), top_level),
        (Some("Sh" | "SH"), true) | (Some("Ss" | "SS"), false)
    )
}
