//! Section/root ownership and source-ordered heading reconstruction.
use super::{
    Block, LoweringContext, Node, NodeKind, Section, first_part_children, lower_blocks,
    lower_inline_nodes, plain_text, section_spacing, source_span, update_paragraph_distance,
};

pub(in crate::mandoc) fn lower_sections(
    root: &Node,
    context: &mut LoweringContext<'_>,
) -> Vec<Section> {
    let mut paragraph_distance = 1;
    let mut sections = Vec::new();
    for node in &root.children {
        update_paragraph_distance(node, &mut paragraph_distance);
        // Accept both `.SH` and a `.SS` that appears directly at the document
        // root. Well-formed pages nest `.SS` inside a `.SH` body, but pages
        // generated by tools such as Pandoc emit only `.SS` blocks with no
        // enclosing `.SH`. Without this, such pages lower to zero sections and
        // the whole document is reported as unreadable.
        if !is_section(node, true) && !is_section(node, false) {
            continue;
        }
        let has_preceding_content = sections.last().is_some_and(section_has_body);
        let spacing_before_lines = section_spacing(
            node,
            sections.is_empty(),
            has_preceding_content,
            paragraph_distance,
        );
        sections.push(lower_section(
            node,
            context,
            spacing_before_lines,
            &mut paragraph_distance,
        ));
    }
    sections
}

/// Lower printable root content that is not owned by a formal section.
///
/// Most manuals contain only metadata and section blocks at the root, but
/// roff also permits ordinary text there. Generated or malformed pages can,
/// for example, indent what looks like a request and thereby make it literal
/// text. Preserve those bytes in `Document::blocks` instead of silently
/// discarding them while discovering sections.
pub(in crate::mandoc) fn lower_root_blocks(
    root: &Node,
    context: &LoweringContext<'_>,
) -> Vec<Block> {
    let mut output = Vec::new();
    let mut paragraph_distance = 1;
    let mut start = 0;
    for (index, node) in root.children.iter().enumerate() {
        if !is_section(node, true) && !is_section(node, false) {
            continue;
        }
        output.extend(lower_blocks(
            &root.children[start..index],
            context,
            crate::mandoc::layout::SourceIndent::default(),
            &mut paragraph_distance,
        ));
        start = index + 1;
    }
    output.extend(lower_blocks(
        &root.children[start..],
        context,
        crate::mandoc::layout::SourceIndent::default(),
        &mut paragraph_distance,
    ));
    output
}

fn lower_section(
    node: &Node,
    context: &mut LoweringContext<'_>,
    spacing_before_lines: u16,
    paragraph_distance: &mut u16,
) -> Section {
    let heading = lower_inline_nodes(
        first_part_children(node, NodeKind::Head),
        context.default_name,
    );
    let title = plain_text(&heading).trim().to_owned();
    // Allocate IDs in visible document order. Besides being deterministic for
    // consumers, this makes `.Sx` resolution independent of tree recursion.
    let (id, fragment_aliases) = context.section_identity_for(&title, node);
    let body = first_part_children(node, NodeKind::Body);
    let first_subsection = body
        .iter()
        .position(|child| is_section(child, false))
        .unwrap_or(body.len());
    let blocks = lower_blocks(
        &body[..first_subsection],
        context,
        crate::mandoc::layout::SourceIndent::default(),
        paragraph_distance,
    );
    let mut children = Vec::new();
    let mut has_preceding_content = !blocks.is_empty();
    for child in &body[first_subsection..] {
        update_paragraph_distance(child, paragraph_distance);
        if !is_section(child, false) {
            continue;
        }
        let child_spacing = section_spacing(
            child,
            children.is_empty(),
            has_preceding_content,
            *paragraph_distance,
        );
        let child = lower_section(child, context, child_spacing, paragraph_distance);
        has_preceding_content = section_has_body(&child);
        children.push(child);
    }
    Section {
        id: id.into(),
        fragment_aliases,
        heading: mant_ir::Heading {
            content: heading,
            source: node
                .children
                .iter()
                .find(|child| child.kind == NodeKind::Head)
                .and_then(source_span),
        },
        spacing_before_lines,
        blocks,
        children,
        source: source_span(node),
    }
}

fn section_has_body(section: &Section) -> bool {
    !section.blocks.is_empty() || section.children.iter().any(section_has_body)
}

pub(super) fn is_section(node: &Node, top_level: bool) -> bool {
    matches!(
        (node.macro_name.as_deref(), top_level),
        (Some("Sh" | "SH"), true) | (Some("Ss" | "SS"), false)
    )
}
