.TH T 1
.IP "\fB\-root\fR" 4
.IP "\fB\-root-long\fR" 4
ROOT_BODY
.SH OPTIONS
.IP "\fB\-a\fR" 4
.PD 0
.IP "\fB\-\-all\fR" 4
SHARED_BODY
.PD
.IP "\fB\-b\fR" 4
.PP
.IP "\fB\-\-broken\fR" 4
BROKEN_BODY
.IP "\fB\-c\fR" 4
OWN_BODY
.IP "\fB\-\-c-long\fR" 4
FOLLOW_BODY
.SH NEXT
.IP "\fB\-d\fR" 4
.SH OTHER
.IP "\fB\-\-d-long\fR" 4
LATE_BODY
