[package]
name = "mant-ui"
autobins = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Ratatui frontend component for ManT"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["man", "markdown", "tui", "ratatui", "documentation"]
categories = ["command-line-utilities", "text-processing"]
include = ["/Cargo.toml", "/LICENSE", "/README.md", "/src/**"]

[dependencies]
crossterm.workspace = true
mant-ir = { path = "../mant-ir", version = "=0.7.0" }
mant-protocol = { path = "../mant-protocol", version = "=0.7.0" }
ratatui.workspace = true
unicode-width.workspace = true

[dev-dependencies]
mant-engine = { path = "../mant-engine", version = "=0.7.0" }

[lints]
workspace = true
