[package]
name = "mant-ui"
autobins = false
version = "0.11.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Ratatui frontend component for ManT"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["man", "markdown", "tui", "ratatui", "documentation"]
categories = ["command-line-utilities", "text-processing"]
include = ["/Cargo.toml", "/LICENSE", "/README.md", "/src/**"]

[dependencies]
crossterm.workspace = true
mant-ir = { path = "../mant-ir", version = "^0.11.0" }
mant-protocol = { path = "../mant-protocol", version = "^0.11.0" }
mant-render = { path = "../mant-render", version = "^0.11.0" }
ratatui.workspace = true
unicode-width.workspace = true

[dev-dependencies]
mant-codec = { path = "../mant-codec", version = "^0.11.0", default-features = false }
mant-engine = { path = "../mant-engine", version = "^0.11.0" }
mant-loader = { path = "../mant-loader", version = "^0.11.0", features = ["roff"] }
mant-query = { path = "../mant-query", version = "^0.11.0", default-features = false }
tokio = { version = "^1", features = ["rt"] }

[lints]
workspace = true
