[package]
name = "mant-ui"
autobins = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Ratatui frontend component for ManT"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["man", "markdown", "tui", "ratatui", "documentation"]
categories = ["command-line-utilities", "text-processing"]
include = ["/Cargo.toml", "/README.md", "/src/**"]

[dependencies]
crossterm.workspace = true
mant-ast = { path = "../mant-ast", version = "=0.4.0" }
mant-core = { path = "../mant-core", version = "=0.4.0" }
ratatui.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
