"""Source-bound gold checks over the existing explanation collector.

This module does not discover or classify declarations. Expectations must be
reviewed against the source/AST, not generated by accepting current output.
Unreviewed probes and missing/drifted inputs remain unresolved, never clean.
"""
from __future__ import annotations

import copy
import hashlib
import json
import re
from collections import Counter
from pathlib import Path

from roff_audit_common import manual_hierarchy_root, run_jsonl_profile_batch, source_digest


def visible(value: object) -> str:
    """Visible text only: never match a body against IDs, paths or metadata."""
    if isinstance(value, list):
        return "".join(visible(item) for item in value)
    if not isinstance(value, dict):
        return ""
    if value.get("type") in {"text", "code"}:
        return value.get("value", "")
    if value.get("type") == "line-break":
        return "\n"
    if value.get("type") in {"anchor", "fragment-alias"}:
        return ""
    text = "".join(visible(value.get(key)) for key in
                   ("children", "items", "terms", "description", "blocks", "rows", "cells"))
    return text + ("\n" if value.get("type") in {"paragraph", "preformatted", "heading"} else "")


def compact(value: object) -> str:
    return " ".join(visible(value).split())


def owner_record(evidence: dict, supports: list | None = None) -> dict:
    entry = evidence.get("entry") or {}
    block = (evidence.get("content") or {}).get("block") or {}
    items = block.get("items", [])
    content = evidence.get("content") or {}
    if content.get("kind") == "declaration-member":
        pool = supports or []
        index, member = content.get("support", -1), content.get("itemIndex", -1)
        if 0 <= index < len(pool):
            group_items = pool[index].get("block", {}).get("items", [])
            if 0 <= member < len(group_items):
                items = [group_items[member]]
    body = items[0].get("description", items[0].get("blocks", [])) if len(items) == 1 else []
    kind = entry.get("kind", {})
    return {
        "source": evidence.get("source"),
        "id": evidence["outline"]["node"]["id"],
        "path": evidence["outline"]["node"]["path"],
        "kind": kind.get("parameterKind", kind.get("kind")),
        "names": entry.get("names", []),
        "forms": [compact(form) for form in entry.get("forms", [])],
        "body": compact(body),
        "emptyDescription": not body,
        "aliasGroups": entry.get("aliasGroups", []),
        "aliasOf": entry.get("aliasOf"),
        "valueDomain": entry.get("valueDomain"),
        "omitted": any(evidence.get(field, False) for field in
                       ("contentOmitted", "detailsOmitted", "matchDetailsOmitted", "nameBindingsOmitted")),
    }


def compare(probe: dict, response: dict) -> tuple[str, list[str], list[dict]]:
    explanation = response.get("explanation") or {}
    supports = explanation.get("supports", [])
    actual = [owner_record(e, supports) for e in explanation.get("evidence", [])
              if e.get("class") == "direct-entry"]
    if "expected" not in probe:
        return "unresolved", ["probe has no reviewed gold"], actual
    expected = probe["expected"]
    errors = []
    total = explanation.get("counts", {}).get("directEntry", {}).get("total")
    if total != len(expected) or len(actual) != len(expected):
        errors.append(f"direct owners: expected {len(expected)}, total={total}, returned={len(actual)}")
    used = set()
    for want in expected:
        matches = [(i, got) for i, got in enumerate(actual)
                   if got["source"] == want["source"] and got["forms"] == want["forms"] and i not in used]
        if len(matches) != 1:
            errors.append(f"source owner {want['source']}: expected exactly one, found {len(matches)}")
            continue
        index, got = matches[0]
        used.add(index)
        for key in ("kind", "names", "forms", "emptyDescription"):
            if got[key] != want[key]:
                errors.append(f"{want['source']} {key}: {got[key]!r} != {want[key]!r}")
        if got["omitted"]:
            errors.append(f"{want['source']}: gold cannot pass on omitted detail/body")
        for text in want.get("bodyIncludes", []):
            if text not in got["body"]:
                errors.append(f"{want['source']}: missing body witness {text!r}")
        if witness := want.get("bodyWitness"):
            prefix = " ".join(got["body"].split()[:witness["words"]])
            if hashlib.sha256(prefix.encode()).hexdigest() != witness["sha256"]:
                errors.append(f"{want['source']}: opening-body witness hash differs")
        for text in want.get("bodyExcludes", []):
            if text in got["body"]:
                errors.append(f"{want['source']}: wrong-owner body {text!r}")
        if not want.get("allowRelationships", False) and any(
                got[key] for key in ("aliasGroups", "aliasOf", "valueDomain")):
            errors.append(f"{want['source']}: undeclared relationship")
    forbidden = set(probe.get("forbiddenNames", []))
    for got in actual:
        if forbidden.intersection(got["names"]):
            errors.append(f"forbidden direct name at {got['source']}")
    if "expectedSupports" in probe:
        expected_supports = probe["expectedSupports"]
        if len(supports) != len(expected_supports):
            errors.append(f"support count: {len(supports)} != {len(expected_supports)}")
        for want in expected_supports:
            matches = [s for s in supports if [item.get("source") for item in s.get("block", {}).get("items", [])] == want["memberSources"]]
            if len(matches) != 1:
                errors.append(f"support member sources: expected one match for {want['memberSources']}")
                continue
            support = matches[0]
            items = support["block"]["items"]
            if [[compact(term) for term in item["terms"]] for item in items] != want["memberForms"]:
                errors.append("support original heads differ")
            body = compact(items[-1].get("description", []))
            for witness in want.get("bodyIncludes", []):
                if witness not in body: errors.append(f"support missing body witness {witness!r}")
            for witness in want.get("bodyWitnesses", []):
                words = body.split()
                at = witness["startWord"]
                sample = " ".join(words[at:at + witness["words"]])
                if hashlib.sha256(sample.encode()).hexdigest() != witness["sha256"]:
                    errors.append(f"support body witness differs at word {at}")
            for witness in want.get("bodyExcludes", []):
                if witness in body: errors.append(f"support crossed boundary: {witness!r}")
            for block_type in want.get("requiredTypes", []):
                if not contains_type(items[-1].get("description", []), block_type):
                    errors.append(f"support missing original {block_type}")
            for item in items:
                entry = item.get("entry") or {}
                if entry.get("aliasGroups") or entry.get("aliasOf"):
                    errors.append("support invented alias relationship")
        if any(e.get("supportOmitted") for e in explanation.get("evidence", [])):
            errors.append("required group context was omitted")
    return ("failure" if errors else "passed"), errors, actual


def contains_type(value: object, kind: str) -> bool:
    if isinstance(value, list):
        return any(contains_type(item, kind) for item in value)
    if isinstance(value, dict):
        return value.get("type") == kind or any(contains_type(item, kind) for item in value.values())
    return False


def run(manifest: Path, profiler: Path, timeout: int, root_overrides: list[str] | None = None,
        fixtures_only: bool = False) -> dict:
    panel = json.loads(manifest.read_text(encoding="utf-8"))
    if panel.get("schema") != "mant.roff-query-gold/v1":
        raise ValueError("unsupported query gold schema")
    roots = dict(panel.get("roots", {}))
    for assignment in root_overrides or []:
        name, separator, path = assignment.partition("=")
        if not separator or name not in roots or not path:
            raise ValueError("--query-root requires a declared ROOT=PATH")
        roots[name] = path
    requests, sources, results = {}, {}, []
    for source in panel["sources"]:
        if fixtures_only and source.get("root") != "checkout":
            continue
        key = source["id"]
        if key in sources:
            raise ValueError(f"duplicate query source {key}")
        sources[key] = source
        path = Path(roots.get(source.get("root"), "")) / source["path"]
        if not path.is_absolute():
            path = manifest.parent / path
        digest = source_digest(path)
        if digest is None or digest != source["sha256"]:
            results.append({"id": key, "status": "unresolved", "reason": "source missing or SHA mismatch"})
            continue
        queries = [probe["query"] for probe in source["queries"]]
        if len(set(queries)) != len(queries) or not queries or len(queries) > 16:
            raise ValueError(f"invalid query list for {key}")
        for probe in source["queries"]:
            if "expected" not in probe:
                continue
            if not probe.get("review") or not isinstance(probe["expected"], list):
                raise ValueError(f"gold requires a review note and owner array: {key}")
            for support in probe.get("expectedSupports", []):
                if not (support.get("bodyIncludes") or support.get("bodyWitnesses")) or len(support.get("memberSources", [])) < 2 or len(support["memberSources"]) != len(support.get("memberForms", [])):
                    raise ValueError(f"support gold requires source members, complete heads and body witnesses: {key}")
                for witness in support.get("bodyWitnesses", []):
                    if not 1 <= witness.get("words", 0) <= 32 or witness.get("startWord", -1) < 0 or not re.fullmatch(r"[0-9a-f]{64}", witness.get("sha256", "")):
                        raise ValueError(f"invalid support body witness: {key}")
            for owner in probe["expected"]:
                if not all(field in owner for field in
                           ("source", "forms", "kind", "names", "emptyDescription")):
                    raise ValueError(f"incomplete gold owner: {key}")
                if not owner["emptyDescription"] and not (owner.get("bodyIncludes") or owner.get("bodyWitness")):
                    raise ValueError(f"nonempty gold owner requires a body witness: {key}")
                if witness := owner.get("bodyWitness"):
                    if not 1 <= witness.get("words", 0) <= 32 or len(witness.get("sha256", "")) != 64:
                        raise ValueError(f"invalid body witness: {key}")
        # A caller-selected corpus root is identity discovery, not permission
        # for arbitrary includes. Keep each parser within its manual hierarchy.
        parent = path.parent.parent if path.parent.name.startswith("man") else path.parent
        root = manual_hierarchy_root(path, [parent]) or path.parent
        requests[key] = {"id": key, "path": str(path), "root": str(root), "queries": queries}
    if not sources:
        raise ValueError("query gold selection is empty")
    responses = run_jsonl_profile_batch(profiler, requests, timeout, "semantic query")
    declaration_profiles = []
    for key, request in requests.items():
        response = responses[key]
        if group_profile := response.get("declarationGroups"):
            declaration_profiles.append({"id": key, "sourceSha256": sources[key]["sha256"],
                "observedGroups": len(group_profile["observedGroups"]),
                "sourceRuns": len(group_profile["sourceRuns"]),
                "decisions": dict(Counter(row["reason"] for row in group_profile["sourceRuns"])),
                "unexpectedGroups": group_profile["unexpectedGroups"],
                "invalidGroups": group_profile["invalidGroups"],
                "unresolvedRuns": group_profile["unresolvedRuns"]})
        rows = response.get("queryProfiles", [])
        if response.get("error") or len(rows) != len(request["queries"]):
            results.append({"id": key, "status": "unresolved", "reason": response.get("error", "incomplete probe response")})
            continue
        for probe, row in zip(sources[key]["queries"], rows, strict=True):
            if probe["query"] != row.get("query"):
                raise ValueError(f"query response order mismatch for {key}")
            status, reasons, actual = compare(probe, row)
            results.append({"id": key, "query": probe["query"], "status": status,
                            "reasons": reasons, "actual": actual,
                            "nativeSourceWitnesses": row.get("nativeSourceWitnesses", [])})
    return {"schema": "mant.roff-query-gold-result/v1", "manifest": str(manifest),
            "sourceCount": len(sources), "uniqueSourceCount": len({s["sha256"] for s in sources.values()}),
            "declarationProfiles": declaration_profiles,
            "results": results, "limitations": "Only reviewed queries are gold; AST coordinates identify candidates, not an automatic proof of ownership."}


def self_check() -> None:
    body = {"type": "paragraph", "children": [{"type": "text", "value": "BODY"}]}
    evidence = {"class": "direct-entry", "source": {"line": 4, "column": 2},
                "outline": {"node": {"id": "x", "path": "1/e1"}},
                "entry": {"kind": {"kind": "command"}, "names": ["x"],
                          "forms": [[{"type": "text", "value": "x ARG"}]]},
                "content": {"block": {"items": [{"description": [body]}]}}}
    want = {"source": {"line": 4, "column": 2}, "kind": "command", "names": ["x"],
            "forms": ["x ARG"], "emptyDescription": False, "bodyIncludes": ["BODY"]}
    probe = {"query": "x", "expected": [want]}
    response = {"explanation": {"counts": {"directEntry": {"total": 1}}, "evidence": [evidence]}}
    assert compare(probe, response)[0] == "passed"
    support = {"kind": "declaration-group", "block": {"items": [
        {"source": {"line": 2, "column": 2}, "terms": [[{"type": "text", "value": "y ARG"}]], "description": []},
        {"source": want["source"], "terms": evidence["entry"]["forms"], "description": [body]},
    ]}}
    supported = copy.deepcopy(response)
    supported["explanation"]["supports"] = [support]
    supported["explanation"]["evidence"][0]["content"] = {"kind": "declaration-member", "support": 0, "itemIndex": 1}
    support_gold = {**probe, "expectedSupports": [{"memberSources": [i["source"] for i in support["block"]["items"]], "memberForms": [["y ARG"], ["x ARG"]], "bodyIncludes": ["BODY"], "requiredTypes": ["paragraph"]}]}
    assert compare(support_gold, supported)[0] == "passed"
    for changed in ("missing", "tail", "owner", "duplicate", "alias"):
        wrong = copy.deepcopy(supported)
        pool = wrong["explanation"]["supports"]
        if changed == "missing": pool.clear()
        elif changed == "tail": pool[0]["block"]["items"][1]["description"] = []
        elif changed == "owner": pool[0]["block"]["items"][1]["source"]["line"] = 99
        elif changed == "duplicate": pool.append(copy.deepcopy(pool[0]))
        else: pool[0]["block"]["items"][0]["entry"] = {"aliasGroups": [["x", "y"]]}
        assert compare(support_gold, wrong)[0] == "failure", changed
    assert compare({"query": "x"}, response)[0] == "unresolved"
    for field, value in [("source", {"line": 8, "column": 2}), ("contentOmitted", True),
                         ("class", "entry-mention"), ("entry", {"kind": {"kind": "term"}})]:
        changed = copy.deepcopy(response)
        changed["explanation"]["evidence"][0][field] = value
        assert compare(probe, changed)[0] == "failure", field
    assert compare({**probe, "expected": [want, want]}, response)[0] == "failure"
    assert compare({**probe, "expected": []}, response)[0] == "failure"
    assert compare({**probe, "forbiddenNames": ["x"]}, response)[0] == "failure"
    assert compare({**probe, "expected": [{**want, "bodyIncludes": ["OTHER"]}]}, response)[0] == "failure"
    hashed = {**want, "bodyIncludes": [], "bodyWitness": {"words": 8, "sha256": hashlib.sha256(b"BODY").hexdigest()}}
    assert compare({**probe, "expected": [hashed]}, response)[0] == "passed"
    hashed["bodyWitness"]["sha256"] = "0" * 64
    assert compare({**probe, "expected": [hashed]}, response)[0] == "failure"
    # Matching metadata is not matching visible body.
    assert compact({"id": "BODY", "sourcePath": "BODY"}) == ""
