"""Source-bound gold checks over the existing explanation collector.

This module does not discover or classify declarations. Expectations must be
reviewed against the source/AST, not generated by accepting current output.
Unreviewed probes and missing/drifted inputs remain unresolved, never clean.
"""
from __future__ import annotations

import copy
import hashlib
import json
import re
from collections import Counter
from pathlib import Path

from roff_audit_common import manual_hierarchy_root, run_jsonl_profile_batch, source_digest


class VisibleReader:
    """Resolve response-local Flow references, never source or display bytes."""

    def __init__(self, projection: object = None) -> None:
        self.projected = projection is not None
        store = projection.get("contentStore") if isinstance(projection, dict) else None
        atoms = store.get("atoms") if isinstance(store, dict) else None
        self.atoms = atoms if isinstance(atoms, list) else None
        self.bytes: dict[int, bytes] = {}

    def text(self, reference: object) -> str:
        if not isinstance(reference, dict) or self.atoms is None:
            raise ValueError("visible content reference has no projection")
        key = reference.get("atom")
        if type(key) is not int or not 1 <= key <= len(self.atoms):
            raise ValueError("visible content atom key is out of range")
        atom = self.atoms[key - 1]
        if (not isinstance(atom, dict) or type(atom.get("key")) is not int
                or atom["key"] != key or atom.get("kind") not in {"text", "whitespace"}):
            raise ValueError("visible content atom is not text")
        if key not in self.bytes:
            text = atom.get("text")
            if not isinstance(text, str):
                raise ValueError("visible content atom has no logical text")
            try:
                self.bytes[key] = text.encode("utf-8")
            except UnicodeEncodeError as error:
                raise ValueError("visible content atom is not valid UTF-8") from error
        span = reference.get("bytes")
        if not isinstance(span, dict):
            raise ValueError("visible content reference has no byte range")
        start, end = span.get("start"), span.get("end")
        if (type(start) is not int or type(end) is not int
                or not 0 <= start <= end <= len(self.bytes[key])):
            raise ValueError("visible content byte range is out of bounds")
        raw = self.bytes[key]
        if any(offset < len(raw) and raw[offset] & 0xC0 == 0x80 for offset in (start, end)):
            raise ValueError("visible content byte range splits a scalar")
        try:
            return raw[start:end].decode("utf-8")
        except UnicodeDecodeError as error:
            raise ValueError("visible content byte range splits a scalar") from error


def visible(value: object, reader: VisibleReader | None = None) -> str:
    """Visible text only: never match a body against IDs, paths or metadata."""
    if isinstance(value, list):
        return "".join(visible(item, reader) for item in value)
    if not isinstance(value, dict):
        return ""
    if value.get("type") in {"text", "code"}:
        if "content" in value:
            return (reader or VisibleReader()).text(value["content"])
        if reader is not None and reader.projected:
            raise ValueError("projected visible leaf has no content reference")
        return value.get("value", "")
    if value.get("type") == "line-break":
        return "\n"
    if value.get("type") in {"anchor", "fragment-alias"}:
        return ""
    text = "".join(visible(value.get(key), reader) for key in
                   ("children", "items", "terms", "description", "blocks", "rows", "cells"))
    return text + ("\n" if value.get("type") in {"paragraph", "preformatted", "heading"} else "")


def compact(value: object, reader: VisibleReader | None = None) -> str:
    return " ".join(visible(value, reader).split())


def expected_source(value: dict) -> dict:
    """Bind legacy single-source gold coordinates to the root SourceKey."""
    return {**value, "source": value.get("source", 1)}


def checked_item(values: object, index: object) -> object:
    """JSON indices never inherit Python's negative or bool indexing rules."""
    if not isinstance(values, list) or type(index) is not int or not 0 <= index < len(values):
        raise ValueError("invalid support index")
    return values[index]


def support_items(support: dict, pool: list) -> list:
    """Resolve typed returned fragments; never rediscover a body by its text."""
    if support.get("kind") == "declaration-group":
        items = support["block"]["items"]
        if not isinstance(items, list) or not all(isinstance(item, dict) for item in items):
            raise ValueError("invalid declaration support items")
        return items
    if support.get("kind") != "contained-declaration-group":
        return []
    parent = checked_item(pool, support.get("support"))
    if parent["kind"] not in {"declaration-group", "owned-entry"}:
        raise ValueError("contained support cannot reference another reference")
    if not support["path"]:
        raise ValueError("invalid contained support path")
    block = source_block(parent["block"], support["path"])
    group = support["group"]
    if group not in block["declarationGroups"]:
        raise ValueError("contained support is not an original group")
    all_items = block["items"]
    start, end = group["startItem"], group["endItem"]
    if (not isinstance(all_items, list) or type(start) is not int or type(end) is not int
            or not 0 <= start <= end <= len(all_items)):
        raise ValueError("invalid contained support range")
    items = all_items[start:end]
    if not all(isinstance(item, dict) for item in items):
        raise ValueError("invalid contained support items")
    if len(items) != len(support["members"]):
        raise ValueError("incomplete contained support")
    return items


def source_block(block: dict, path: list) -> dict:
    """Follow the same typed source coordinates as the response contract."""
    if len(path) % 2:
        raise ValueError("invalid source path")
    for slot in range(0, len(path), 2):
        owner, child = path[slot:slot + 2]
        if not isinstance(owner, dict) or not isinstance(child, dict):
            raise ValueError("invalid contained support path")
        if child["kind"] != "block":
            raise ValueError("item/cell path must select a block")
        if owner["kind"] == "definition-item":
            blocks = checked_item(block["items"], owner["index"])["description"]
        elif owner["kind"] == "list-item":
            blocks = checked_item(block["items"], owner["index"])["blocks"]
        elif owner["kind"] == "table-cell":
            blocks = checked_item(checked_item(block["rows"], owner["row"])["cells"], owner["column"])["blocks"]
        else:
            raise ValueError("invalid contained support owner")
        block = checked_item(blocks, child["index"])
    return block


def owner_record(evidence: dict, supports: list | None = None,
                 reader: VisibleReader | None = None) -> dict:
    entry = evidence.get("entry") or {}
    block = (evidence.get("content") or {}).get("block") or {}
    items = block.get("items", [])
    content = evidence.get("content") or {}
    if content.get("kind") == "declaration-member":
        pool = supports or []
        index, member = content.get("support", -1), content.get("itemIndex", -1)
        group_items = support_items(checked_item(pool, index), pool)
        items = [checked_item(group_items, member)]
    elif content.get("kind") == "shared-entry":
        parent = checked_item(supports or [], content["support"])
        if parent["kind"] not in {"declaration-group", "owned-entry"}:
            raise ValueError("shared entry requires a materialized fragment")
        block = source_block(parent["block"], content["path"])
        items = [checked_item(block["items"], content["itemIndex"])]
    body = items[0].get("description", items[0].get("blocks", [])) if len(items) == 1 else []
    kind = entry.get("kind", {})
    return {
        "source": evidence.get("source"),
        "id": evidence["outline"]["node"]["id"],
        "path": evidence["outline"]["node"]["path"],
        "kind": kind.get("parameterKind", kind.get("kind")),
        "names": entry.get("names", []),
        "forms": [compact(form, reader) for form in entry.get("forms", [])],
        "body": compact(body, reader),
        "emptyDescription": not body,
        "aliasGroups": entry.get("aliasGroups", []),
        "aliasOf": entry.get("aliasOf"),
        "valueDomain": entry.get("valueDomain"),
        "omitted": any(evidence.get(field, False) for field in
                       ("contentOmitted", "detailsOmitted", "matchDetailsOmitted", "nameBindingsOmitted")),
    }


def compare(probe: dict, response: dict) -> tuple[str, list[str], list[dict]]:
    explanation = response.get("explanation") or {}
    supports = explanation.get("supports", [])
    reader = VisibleReader(explanation.get("contentProjection"))
    try:
        actual = [owner_record(e, supports, reader) for e in explanation.get("evidence", [])
                  if e.get("class") == "direct-entry"]
    except (ValueError, KeyError, IndexError, TypeError, AttributeError) as error:
        return "unresolved", [str(error)], []
    if "expected" not in probe:
        return "unresolved", ["probe has no reviewed gold"], actual
    expected = probe["expected"]
    errors = []
    total = explanation.get("counts", {}).get("directEntry", {}).get("total")
    if total != len(expected) or len(actual) != len(expected):
        errors.append(f"direct owners: expected {len(expected)}, total={total}, returned={len(actual)}")
    used = set()
    for want in expected:
        matches = [(i, got) for i, got in enumerate(actual)
                   if got["source"] == expected_source(want["source"])
                   and got["forms"] == want["forms"] and i not in used]
        if len(matches) != 1:
            errors.append(f"source owner {want['source']}: expected exactly one, found {len(matches)}")
            continue
        index, got = matches[0]
        used.add(index)
        for key in ("kind", "names", "forms", "emptyDescription"):
            if got[key] != want[key]:
                errors.append(f"{want['source']} {key}: {got[key]!r} != {want[key]!r}")
        if got["omitted"]:
            errors.append(f"{want['source']}: gold cannot pass on omitted detail/body")
        for text in want.get("bodyIncludes", []):
            if text not in got["body"]:
                errors.append(f"{want['source']}: missing body witness {text!r}")
        if witness := want.get("bodyWitness"):
            prefix = " ".join(got["body"].split()[:witness["words"]])
            if hashlib.sha256(prefix.encode()).hexdigest() != witness["sha256"]:
                errors.append(f"{want['source']}: opening-body witness hash differs")
        for text in want.get("bodyExcludes", []):
            if text in got["body"]:
                errors.append(f"{want['source']}: wrong-owner body {text!r}")
        if not want.get("allowRelationships", False) and any(
                got[key] for key in ("aliasGroups", "aliasOf", "valueDomain")):
            errors.append(f"{want['source']}: undeclared relationship")
    forbidden = set(probe.get("forbiddenNames", []))
    for got in actual:
        if forbidden.intersection(got["names"]):
            errors.append(f"forbidden direct name at {got['source']}")
    if "expectedSupports" in probe:
        expected_supports = probe["expectedSupports"]
        try:
            groups = [s for s in supports if s["kind"] != "owned-entry"]
        except (KeyError, TypeError, AttributeError) as error:
            return "unresolved", [str(error)], actual
        if len(groups) != len(expected_supports):
            errors.append(f"support count: {len(groups)} != {len(expected_supports)}")
        for want in expected_supports:
            member_sources = [expected_source(source) for source in want["memberSources"]]
            try:
                matches = [
                    support for support in groups
                    if [item.get("source")
                        for item in support_items(support, supports)] == member_sources
                ]
            except (ValueError, KeyError, IndexError, TypeError, AttributeError) as error:
                return "unresolved", [str(error)], actual
            if len(matches) != 1:
                errors.append(f"support member sources: expected one match for {want['memberSources']}")
                continue
            support = matches[0]
            try:
                items = support_items(support, supports)
            except (ValueError, KeyError, IndexError, TypeError, AttributeError) as error:
                return "unresolved", [str(error)], actual
            try:
                member_forms = [[compact(term, reader) for term in item["terms"]] for item in items]
                body = compact(items[-1].get("description", []), reader)
            except (ValueError, KeyError, IndexError, TypeError, AttributeError) as error:
                return "unresolved", [str(error)], actual
            if member_forms != want["memberForms"]:
                errors.append("support original heads differ")
            for witness in want.get("bodyIncludes", []):
                if witness not in body: errors.append(f"support missing body witness {witness!r}")
            for witness in want.get("bodyWitnesses", []):
                words = body.split()
                at = witness["startWord"]
                sample = " ".join(words[at:at + witness["words"]])
                if hashlib.sha256(sample.encode()).hexdigest() != witness["sha256"]:
                    errors.append(f"support body witness differs at word {at}")
            for witness in want.get("bodyExcludes", []):
                if witness in body: errors.append(f"support crossed boundary: {witness!r}")
            for block_type in want.get("requiredTypes", []):
                if not contains_type(items[-1].get("description", []), block_type):
                    errors.append(f"support missing original {block_type}")
            for item in items:
                entry = item.get("entry") or {}
                if entry.get("aliasGroups") or entry.get("aliasOf"):
                    errors.append("support invented alias relationship")
        if any(e.get("supportOmitted") for e in explanation.get("evidence", [])):
            errors.append("required group context was omitted")
    return ("failure" if errors else "passed"), errors, actual


def contains_type(value: object, kind: str) -> bool:
    if isinstance(value, list):
        return any(contains_type(item, kind) for item in value)
    if isinstance(value, dict):
        return value.get("type") == kind or any(contains_type(item, kind) for item in value.values())
    return False


def run(manifest: Path, profiler: Path, timeout: int, root_overrides: list[str] | None = None,
        fixtures_only: bool = False) -> dict:
    panel = json.loads(manifest.read_text(encoding="utf-8"))
    if panel.get("schema") != "mant.roff-query-gold/v1":
        raise ValueError("unsupported query gold schema")
    roots = dict(panel.get("roots", {}))
    for assignment in root_overrides or []:
        name, separator, path = assignment.partition("=")
        if not separator or name not in roots or not path:
            raise ValueError("--query-root requires a declared ROOT=PATH")
        roots[name] = path
    requests, sources, results = {}, {}, []
    for source in panel["sources"]:
        if fixtures_only and source.get("root") != "checkout":
            continue
        key = source["id"]
        if key in sources:
            raise ValueError(f"duplicate query source {key}")
        sources[key] = source
        path = Path(roots.get(source.get("root"), "")) / source["path"]
        if not path.is_absolute():
            path = manifest.parent / path
        digest = source_digest(path)
        if digest is None or digest != source["sha256"]:
            results.append({"id": key, "status": "unresolved", "reason": "source missing or SHA mismatch"})
            continue
        queries = [probe["query"] for probe in source["queries"]]
        if len(set(queries)) != len(queries) or not queries or len(queries) > 16:
            raise ValueError(f"invalid query list for {key}")
        for probe in source["queries"]:
            if "expected" not in probe:
                continue
            if not probe.get("review") or not isinstance(probe["expected"], list):
                raise ValueError(f"gold requires a review note and owner array: {key}")
            for support in probe.get("expectedSupports", []):
                if not (support.get("bodyIncludes") or support.get("bodyWitnesses")) or len(support.get("memberSources", [])) < 2 or len(support["memberSources"]) != len(support.get("memberForms", [])):
                    raise ValueError(f"support gold requires source members, complete heads and body witnesses: {key}")
                for witness in support.get("bodyWitnesses", []):
                    if not 1 <= witness.get("words", 0) <= 32 or witness.get("startWord", -1) < 0 or not re.fullmatch(r"[0-9a-f]{64}", witness.get("sha256", "")):
                        raise ValueError(f"invalid support body witness: {key}")
            for owner in probe["expected"]:
                if not all(field in owner for field in
                           ("source", "forms", "kind", "names", "emptyDescription")):
                    raise ValueError(f"incomplete gold owner: {key}")
                if not owner["emptyDescription"] and not (owner.get("bodyIncludes") or owner.get("bodyWitness")):
                    raise ValueError(f"nonempty gold owner requires a body witness: {key}")
                if witness := owner.get("bodyWitness"):
                    if not 1 <= witness.get("words", 0) <= 32 or len(witness.get("sha256", "")) != 64:
                        raise ValueError(f"invalid body witness: {key}")
        # A caller-selected corpus root is identity discovery, not permission
        # for arbitrary includes. Keep each parser within its manual hierarchy.
        parent = path.parent.parent if path.parent.name.startswith("man") else path.parent
        root = manual_hierarchy_root(path, [parent]) or path.parent
        requests[key] = {"id": key, "path": str(path), "root": str(root), "queries": queries}
    if not sources:
        raise ValueError("query gold selection is empty")
    responses = run_jsonl_profile_batch(profiler, requests, timeout, "semantic query")
    declaration_profiles = []
    for key, request in requests.items():
        response = responses[key]
        if group_profile := response.get("declarationGroups"):
            declaration_profiles.append({"id": key, "sourceSha256": sources[key]["sha256"],
                "observedGroups": len(group_profile["observedGroups"]),
                "sourceRuns": len(group_profile["sourceRuns"]),
                "decisions": dict(Counter(row["reason"] for row in group_profile["sourceRuns"])),
                "unexpectedGroups": group_profile["unexpectedGroups"],
                "invalidGroups": group_profile["invalidGroups"],
                "unresolvedRuns": group_profile["unresolvedRuns"],
                # Source runs without a final declaration group are a census
                # count, not a review failure: roff has no group construct.
                "ungroupedRuns": group_profile.get("ungroupedRuns", 0)})
        rows = response.get("queryProfiles", [])
        if response.get("error") or len(rows) != len(request["queries"]):
            results.append({"id": key, "status": "unresolved", "reason": response.get("error", "incomplete probe response")})
            continue
        for probe, row in zip(sources[key]["queries"], rows, strict=True):
            if probe["query"] != row.get("query"):
                raise ValueError(f"query response order mismatch for {key}")
            status, reasons, actual = compare(probe, row)
            results.append({"id": key, "query": probe["query"], "status": status,
                            "reasons": reasons, "actual": actual,
                            "nativeSourceWitnesses": row.get("nativeSourceWitnesses", [])})
    return {"schema": "mant.roff-query-gold-result/v1", "manifest": str(manifest),
            "sourceCount": len(sources), "uniqueSourceCount": len({s["sha256"] for s in sources.values()}),
            "declarationProfiles": declaration_profiles,
            "results": results, "limitations": "Only reviewed queries are gold; AST coordinates identify candidates, not an automatic proof of ownership."}


def self_check() -> None:
    body = {"type": "paragraph", "children": [{"type": "text", "value": "BODY"}]}
    evidence = {"class": "direct-entry",
                "source": {"source": 1, "line": 4, "column": 2},
                "outline": {"node": {"id": "x", "path": "1/e1"}},
                "entry": {"kind": {"kind": "command"}, "names": ["x"],
                          "forms": [[{"type": "text", "value": "x ARG"}]]},
                "content": {"block": {"items": [{"description": [body]}]}}}
    want = {"source": {"line": 4, "column": 2}, "kind": "command", "names": ["x"],
            "forms": ["x ARG"], "emptyDescription": False, "bodyIncludes": ["BODY"]}
    probe = {"query": "x", "expected": [want]}
    response = {"explanation": {"counts": {"directEntry": {"total": 1}}, "evidence": [evidence]}}
    assert compare(probe, response)[0] == "passed"
    support = {"kind": "declaration-group", "block": {"items": [
        {"source": {"source": 1, "line": 2, "column": 2},
         "terms": [[{"type": "text", "value": "y ARG"}]], "description": []},
        {"source": {**want["source"], "source": 1},
         "terms": evidence["entry"]["forms"], "description": [body]},
    ]}}
    supported = copy.deepcopy(response)
    supported["explanation"]["supports"] = [support]
    supported["explanation"]["evidence"][0]["content"] = {"kind": "declaration-member", "support": 0, "itemIndex": 1}
    support_gold = {**probe, "expectedSupports": [{
        "memberSources": [{"line": 2, "column": 2}, want["source"]],
        "memberForms": [["y ARG"], ["x ARG"]],
        "bodyIncludes": ["BODY"], "requiredTypes": ["paragraph"],
    }]}
    assert compare(support_gold, supported)[0] == "passed"
    for changed in ("missing", "tail", "owner", "duplicate", "alias"):
        wrong = copy.deepcopy(supported)
        pool = wrong["explanation"]["supports"]
        if changed == "missing": pool.clear()
        elif changed == "tail": pool[0]["block"]["items"][1]["description"] = []
        elif changed == "owner": pool[0]["block"]["items"][1]["source"]["line"] = 99
        elif changed == "duplicate": pool.append(copy.deepcopy(pool[0]))
        else: pool[0]["block"]["items"][0]["entry"] = {"aliasGroups": [["x", "y"]]}
        assert compare(support_gold, wrong)[0] == ("unresolved" if changed == "missing" else "failure"), changed
    invalid_path = copy.deepcopy(supported)
    invalid_path["explanation"]["supports"].append({
        "kind": "contained-declaration-group", "support": 0,
        "path": [{"kind": "definition-item", "index": -1}, {"kind": "block", "index": 0}],
        "group": {}, "members": [],
    })
    invalid_path["explanation"]["evidence"][0]["content"]["support"] = 1
    assert compare(support_gold, invalid_path)[0] == "unresolved"
    invalid_items = copy.deepcopy(supported)
    invalid_items["explanation"]["supports"][0]["block"]["items"] = {}
    assert compare(support_gold, invalid_items)[0] == "unresolved"
    assert compare({"query": "x"}, response)[0] == "unresolved"
    for field, value in [("source", {"line": 8, "column": 2}), ("contentOmitted", True),
                         ("class", "entry-mention"), ("entry", {"kind": {"kind": "term"}})]:
        changed = copy.deepcopy(response)
        changed["explanation"]["evidence"][0][field] = value
        assert compare(probe, changed)[0] == "failure", field
    assert compare({**probe, "expected": [want, want]}, response)[0] == "failure"
    wrong_source = copy.deepcopy(response)
    wrong_source["explanation"]["evidence"][0]["source"]["source"] = 2
    assert compare(probe, wrong_source)[0] == "failure"
    assert compare({**probe, "expected": []}, response)[0] == "failure"
    assert compare({**probe, "forbiddenNames": ["x"]}, response)[0] == "failure"
    assert compare({**probe, "expected": [{**want, "bodyIncludes": ["OTHER"]}]}, response)[0] == "failure"
    hashed = {**want, "bodyIncludes": [], "bodyWitness": {"words": 8, "sha256": hashlib.sha256(b"BODY").hexdigest()}}
    assert compare({**probe, "expected": [hashed]}, response)[0] == "passed"
    hashed["bodyWitness"]["sha256"] = "0" * 64
    assert compare({**probe, "expected": [hashed]}, response)[0] == "failure"
    # Matching metadata is not matching visible body.
    assert compact({"id": "BODY", "sourcePath": "BODY"}) == ""
    projected = copy.deepcopy(response)
    projected["explanation"]["contentProjection"] = {"contentStore": {"atoms": [
        {"key": 1, "kind": "text", "text": "x ARG"},
        {"key": 2, "kind": "text", "text": "BODY中"},
    ]}}
    projected["explanation"]["evidence"][0]["entry"]["forms"] = [[
        {"type": "text", "content": {"atom": 1, "bytes": {"start": 0, "end": 5}}},
    ]]
    projected["explanation"]["evidence"][0]["content"]["block"]["items"][0]["description"][0]["children"] = [
        {"type": "text", "content": {"atom": 2, "bytes": {"start": 0, "end": 4}}},
    ]
    assert compare(probe, projected)[0] == "passed"
    selected = projected["explanation"]["evidence"][0]["content"]["block"]["items"][0]["description"][0]["children"][0]
    selected["content"]["bytes"] = {"start": 4, "end": 5}
    assert compare(probe, projected)[0] == "unresolved"
    selected["content"]["bytes"] = {"start": 5, "end": 5}
    assert compare(probe, projected)[0] == "unresolved"
    selected["content"]["bytes"] = {"start": 0, "end": 4}
    projected["explanation"]["contentProjection"]["contentStore"]["atoms"][0]["key"] = True
    assert compare(probe, projected)[0] == "unresolved"
    projected["explanation"]["contentProjection"]["contentStore"]["atoms"][0]["key"] = 1
    del projected["explanation"]["contentProjection"]
    assert compare(probe, projected)[0] == "unresolved"
