//! Typed roff(7) requests, including preprocessing-only requests from the pinned token registry.

define_family! {
    /// All named roff(7) requests, including preprocessing-only requests in the pinned CVS registry.
    ///
    /// Variants are Rust identities, not upstream numeric token values.
    pub enum RoffMacro {
        Br => "br",
        Ce => "ce",
        Fi => "fi",
        Ft => "ft",
        Ll => "ll",
        Mc => "mc",
        Nf => "nf",
        Po => "po",
        Rj => "rj",
        Sp => "sp",
        Ta => "ta",
        Ti => "ti",
        Ab => "ab",
        Ad => "ad",
        Af => "af",
        Aln => "aln",
        Als => "als",
        Am => "am",
        Am1 => "am1",
        Ami => "ami",
        Ami1 => "ami1",
        As => "as",
        As1 => "as1",
        Asciify => "asciify",
        Backtrace => "backtrace",
        Bd => "bd",
        Bleedat => "bleedat",
        Blm => "blm",
        Box => "box",
        Boxa => "boxa",
        Bp => "bp",
        BP => "BP",
        Break => "break",
        Breakchar => "breakchar",
        Brnl => "brnl",
        Brp => "brp",
        Brpnl => "brpnl",
        C2 => "c2",
        Cc => "cc",
        Cf => "cf",
        Cflags => "cflags",
        Ch => "ch",
        Char => "char",
        Chop => "chop",
        Class => "class",
        Close => "close",
        Cl => "CL",
        Color => "color",
        Composite => "composite",
        Continue => "continue",
        Cp => "cp",
        Cropat => "cropat",
        Cs => "cs",
        Cu => "cu",
        Da => "da",
        Dch => "dch",
        Dd => "Dd",
        De => "de",
        De1 => "de1",
        Defcolor => "defcolor",
        Dei => "dei",
        Dei1 => "dei1",
        Device => "device",
        Devicem => "devicem",
        Di => "di",
        Do => "do",
        Ds => "ds",
        Ds1 => "ds1",
        Dwh => "dwh",
        Dt => "dt",
        Ec => "ec",
        Ecr => "ecr",
        Ecs => "ecs",
        El => "el",
        Em => "em",
        En => "EN",
        Eo => "eo",
        Ep => "EP",
        Eq => "EQ",
        Errprint => "errprint",
        Ev => "ev",
        Evc => "evc",
        Ex => "ex",
        Fallback => "fallback",
        Fam => "fam",
        Fc => "fc",
        Fchar => "fchar",
        Fcolor => "fcolor",
        Fdeferlig => "fdeferlig",
        Feature => "feature",
        Fkern => "fkern",
        Fl => "fl",
        Flig => "flig",
        Fp => "fp",
        Fps => "fps",
        Fschar => "fschar",
        Fspacewidth => "fspacewidth",
        Fspecial => "fspecial",
        Ftr => "ftr",
        Fzoom => "fzoom",
        Gcolor => "gcolor",
        Hc => "hc",
        Hcode => "hcode",
        Hidechar => "hidechar",
        Hla => "hla",
        Hlm => "hlm",
        Hpf => "hpf",
        Hpfa => "hpfa",
        Hpfcode => "hpfcode",
        Hw => "hw",
        Hy => "hy",
        Hydefault => "hydefault",
        Hylang => "hylang",
        Hylen => "hylen",
        Hym => "hym",
        Hypp => "hypp",
        Hys => "hys",
        Ie => "ie",
        If => "if",
        Ig => "ig",
        Index => "index",
        It => "it",
        Itc => "itc",
        Ix => "IX",
        Kern => "kern",
        Kernafter => "kernafter",
        Kernbefore => "kernbefore",
        Kernpair => "kernpair",
        Lc => "lc",
        LcCtype => "lc_ctype",
        Lds => "lds",
        Length => "length",
        Letadj => "letadj",
        Lf => "lf",
        Lg => "lg",
        Lhang => "lhang",
        Linetabs => "linetabs",
        Lnr => "lnr",
        Lnrf => "lnrf",
        Lpfx => "lpfx",
        Ls => "ls",
        Lsm => "lsm",
        Lt => "lt",
        Mediasize => "mediasize",
        Minss => "minss",
        Mk => "mk",
        Mso => "mso",
        Msoquiet => "msoquiet",
        Na => "na",
        Ne => "ne",
        Nh => "nh",
        Nhychar => "nhychar",
        Nm => "nm",
        Nn => "nn",
        Nop => "nop",
        Nr => "nr",
        Nrf => "nrf",
        Nroff => "nroff",
        Ns => "ns",
        Nx => "nx",
        Open => "open",
        Opena => "opena",
        Os => "os",
        Output => "output",
        Padj => "padj",
        Papersize => "papersize",
        Pc => "pc",
        Pchar => "pchar",
        Pcolor => "pcolor",
        Pcomposite => "pcomposite",
        Pev => "pev",
        Phw => "phw",
        Pi => "pi",
        PI => "PI",
        Pl => "pl",
        Pline => "pline",
        Pm => "pm",
        Pn => "pn",
        Pnr => "pnr",
        Ps => "ps",
        Psbb => "psbb",
        Pshape => "pshape",
        Pso => "pso",
        Pstream => "pstream",
        Ptr => "ptr",
        Pvs => "pvs",
        Pwh => "pwh",
        Rchar => "rchar",
        Rd => "rd",
        Recursionlimit => "recursionlimit",
        Return => "return",
        Rfschar => "rfschar",
        Rhang => "rhang",
        Rm => "rm",
        Rn => "rn",
        Rnn => "rnn",
        Rr => "rr",
        Rs => "rs",
        Rt => "rt",
        Schar => "schar",
        Sentchar => "sentchar",
        Shc => "shc",
        Shift => "shift",
        Sizes => "sizes",
        So => "so",
        Soquiet => "soquiet",
        Spacewidth => "spacewidth",
        Special => "special",
        Spreadwarn => "spreadwarn",
        Ss => "ss",
        Stringdown => "stringdown",
        Stringup => "stringup",
        Sty => "sty",
        Substring => "substring",
        Sv => "sv",
        Sy => "sy",
        TAnd => "T&",
        Tc => "tc",
        Te => "TE",
        Th => "TH",
        Tkf => "tkf",
        Tl => "tl",
        Tm => "tm",
        Tm1 => "tm1",
        Tmc => "tmc",
        Tr => "tr",
        Track => "track",
        Transchar => "transchar",
        Trf => "trf",
        Trimat => "trimat",
        Trin => "trin",
        Trnt => "trnt",
        Troff => "troff",
        Ts => "TS",
        Uf => "uf",
        Ul => "ul",
        Unformat => "unformat",
        Unwatch => "unwatch",
        Unwatchn => "unwatchn",
        Vpt => "vpt",
        Vs => "vs",
        Warn => "warn",
        Warnscale => "warnscale",
        Watch => "watch",
        Watchlength => "watchlength",
        Watchn => "watchn",
        Wh => "wh",
        While => "while",
        Write => "write",
        Writec => "writec",
        Writem => "writem",
        Xflag => "xflag",
        BlockEnd => ".",
    }
}

impl RoffMacro {
    /// Whether the pinned parser retains this request as a formatter node.
    ///
    /// Preprocessing-only requests are executed before the completed AST is
    /// transferred and do not enter its formatter traversal.
    #[must_use]
    pub const fn generates_node(self) -> bool {
        // roff.h ends the node-producing range at ROFF_MAX. In
        // mdoc_term.c::print_mdoc_node(), tokens below that boundary go to
        // roff_term_pre() rather than the mdoc pre/children/post lifecycle.
        matches!(
            self,
            Self::Br
                | Self::Ce
                | Self::Fi
                | Self::Ft
                | Self::Ll
                | Self::Mc
                | Self::Nf
                | Self::Po
                | Self::Rj
                | Self::Sp
                | Self::Ta
                | Self::Ti
        )
    }
}
